version: "3.7"
services:
        
  mediawiki-private:
    image: bordercloud/rockylinux-apache-php-mariadb-rdfunit
    hostname: serverdev-mediawiki1.localdomain
    container_name: instance1.rockylinux-apache-php-mariadb-rdfunit
    privileged: true
    networks:
      mediawiki-ci:
        ipv4_address: 172.19.0.2
    extra_hosts:
        - "serverdev-mediawiki2.localdomain:172.19.0.3"
        - "database-test1.localdomain:172.19.0.4"
        - "database-test2.localdomain:172.19.0.5"
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
      - "${MW1_PATH:-./}:/var/www/mediawiki:ro"
      - "${MW1_PATH:-./}/vhost.conf:/etc/httpd/conf.d/vhost.conf:ro"
      - "$PWD/config:/config:ro"
      - "${PWD}/coverage/tools:/coverage/tools:ro"
      - "${PWD}/coverage/mediawiki1/log:/coverage/log"
      - "${PWD}/coverage/mediawiki1/report:/coverage/report"
    env_file:
      - '.env'
    environment:
      XDEBUG_CONFIG: '${XDEBUG_CONFIG}'
      TERM: 'xterm'
      
  mediawiki-public:
    image: bordercloud/rockylinux-apache-php-mariadb-rdfunit
    hostname: serverdev-mediawiki2.localdomain
    container_name: instance2.rockylinux-apache-php-mariadb-rdfunit
    privileged: true
    networks:
      mediawiki-ci:
        ipv4_address: 172.19.0.3
    extra_hosts:
        - "serverdev-mediawiki1.localdomain:172.19.0.2"
        - "database-test1.localdomain:172.19.0.4"
        - "database-test2.localdomain:172.19.0.5"
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
      - "${MW2_PATH:-./}:/var/www/mediawiki:ro"
      - "${MW2_PATH:-./}/vhost.conf:/etc/httpd/conf.d/vhost.conf:ro"
      - "$PWD/config:/config:ro"
      - "${PWD}/coverage/tools:/coverage/tools:ro"
      - "${PWD}/coverage/mediawiki2/log:/coverage/log"
      - "${PWD}/coverage/mediawiki2/report:/coverage/report"
    env_file:
      - '.env'
    environment:
      XDEBUG_CONFIG: '${XDEBUG_CONFIG}'
      TERM: 'xterm'

  database-mediawiki-private:
    image: bordercloud/rockylinux-virtuoso7
    hostname: database-test1.localdomain
    container_name: instance1.rockylinux-virtuoso7
    privileged: true
    networks:
      mediawiki-ci:
        ipv4_address: 172.19.0.4
        
  database-mediawiki-public:
    image: bordercloud/rockylinux-virtuoso7
    hostname: database-test2.localdomain
    container_name: instance2.rockylinux-virtuoso7
    privileged: true
    networks:
      mediawiki-ci:
        ipv4_address: 172.19.0.5
      
networks:
  mediawiki-ci:
    ipam:
      config:
        - subnet: 172.19.0.0/16

