name: MediaWiki 1.38 trigger

on:
  workflow_run:
    workflows: ["MediaWiki 1.X event"]
    types: [completed]
  schedule:
    - cron:  '20 5 * * *'

  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - run: ./checkUpdatesForAllDependencies.sh REL1_38
      
