name: MediaWiki 1.36 trigger

on:
  workflow_run:
    workflows: ["MediaWiki 1.X event"]
    types: [completed]
  schedule:
    - cron:  '10 5 * * *'

  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: ./checkUpdatesForAllDependencies.sh REL1_36
      
