name: Publish database

on: workflow_dispatch

env:
    VERSION: "" 
      
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - 
        name: Check out the repo
        uses: actions/checkout@v2
      - 
        name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      -
        name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: bordercloud/rockylinux-virtuoso7
      - 
        name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          file: ./docker/rockylinux-virtuoso7/Dockerfile
          context: ./docker/rockylinux-virtuoso7
          push: true
          tags: |
            bordercloud/rockylinux-virtuoso7:latest
      #-
        #name: Push README to Dockerhub
        #uses: christian-korneck/update-container-description-action@v1
        #env:
          #DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}
          #DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
        #with:
          #destination_container_repo: bordercloud/rockylinux-virtuoso7
          #provider: dockerhub
          #short_description: 'bordercloud/rockylinux-virtuoso7'
          #readme_file: 'README.md'
