name: Test coverage mode
      
on: workflow_dispatch

env:
    VERSION: "" 
      
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - 
        name: Check out the repo
        uses: actions/checkout@v3
        
      #- name: Build image docker
        #run: >-
            #docker build -f docker/rockylinux-apache-php-mariadb-rdfunit/Dockerfile  -t rockylinux-apache-php-mariadb-rdfunit . 
        
      - name: Pull image docker
        run: |
            docker pull bordercloud/rockylinux-apache-php-mariadb-rdfunit

      - name: Run image
        run: |
            docker run --privileged --name  instance.rockylinux-apache-php-mariadb-rdfunit \
            -h rockylinux-apache-php-mariadb-rdfunit \
            -ti \
            -v "/sys/fs/cgroup:/sys/fs/cgroup:ro" \
            -v "${PWD}/servers/mediawiki1:/var/www/mediawiki:ro" \
            -v "${PWD}/servers/mediawiki1/vhost.conf:/etc/httpd/conf.d/vhost.conf:ro" \
            -v "${PWD}/config:/config:ro" \
            -v "${PWD}/coverage/tools:/coverage/tools:ro" \
            -v "${PWD}/coverage/mediawiki1/log:/coverage/log" \
            -v "${PWD}/coverage/mediawiki1/report:/coverage/report" \
            -d bordercloud/rockylinux-apache-php-mariadb-rdfunit
            
      - name: Enable the coverage
        run: |
            echo 'sed -i "s/;auto_prepend_file =/auto_prepend_file =/" /etc/php.ini && sed -i "s/;auto_append_file =/auto_append_file =/" /etc/php.ini && sed -i "s/xdebug.mode = off/xdebug.mode = coverage/" /etc/php.d/xdebug.ini && systemctl restart php-fpm && chown apache:apache /coverage/log -R && chmod -R o+r /coverage/log'  | docker exec -i instance.rockylinux-apache-php-mariadb-rdfunit bash
            echo 'ls /coverage/tools'  | docker exec -i instance.rockylinux-apache-php-mariadb-rdfunit bash > coverageFolder.txt
            echo 'cat /etc/php.ini'  | docker exec -i instance.rockylinux-apache-php-mariadb-rdfunit bash > php.ini
            echo 'cat /etc/php.d/xdebug.ini'  | docker exec -i instance.rockylinux-apache-php-mariadb-rdfunit bash > xdebug.ini
            echo 'php -i'  | docker exec -i instance.rockylinux-apache-php-mariadb-rdfunit bash > phpconfig.ini
            cat coverageFolder.txt
            cat php.ini
            cat xdebug.ini
            cat phpconfig.ini

      - name: Create and execute a Web page
        run: |
            mkdir -p ./servers/mediawiki1/htdocs
            echo "<?php phpinfo();" > ./servers/mediawiki1/htdocs/index.php
            wget http://172.17.0.2/index.php
            cat index.php
            
      - name: Check the coverage
        run: |
            mkdir -p ./coverage/mediawiki2/log
            mkdir -p ./coverage/log
            mkdir -p ./coverage/report
            ls -al ./coverage/mediawiki1/log
            echo 'chmod -R o+r /coverage/log'  | docker exec -i instance.rockylinux-apache-php-mariadb-rdfunit bash
            ls -al ./coverage/mediawiki1/log
            php coverage/tools/createGlobalReport.php || true
            
      - name: Check log
        run: |
            ls ./coverage/mediawiki1/log
            ls ./coverage/log
            ls ./coverage/report
            cat ./coverage/report/clover.xml
